2017-02-13 09:11:38,257 - pi3diamond.<module> - INFO - Starting logger.
2017-02-13 09:12:53,209 - emod.start - INFO - Starting Job Manager.
2017-02-13 09:12:53,239 - cron.run - INFO - Starting Cron Daemon.
2017-02-13 09:24:42,280 - pi3diamond.<module> - INFO - Starting logger.
2017-02-13 09:25:17,151 - emod.start - INFO - Starting Job Manager.
2017-02-13 09:25:17,180 - cron.run - INFO - Starting Cron Daemon.
2017-02-13 09:39:42,752 - pi3diamond.<module> - INFO - Starting logger.
2017-02-13 09:39:46,022 - emod.start - INFO - Starting Job Manager.
2017-02-13 09:39:46,022 - cron.run - INFO - Starting Cron Daemon.
2017-02-13 09:43:07,802 - pi3diamond.<module> - INFO - Starting logger.
2017-02-13 09:43:09,601 - emod.start - INFO - Starting Job Manager.
2017-02-13 09:43:09,601 - cron.run - INFO - Starting Cron Daemon.
2017-02-13 10:04:29,084 - auto_focus.focus - INFO - Focus: 33.22, 2.11, -3.14
2017-02-13 10:04:34,753 - auto_focus.focus - INFO - Focus: 33.22, 2.11, -2.69
2017-02-13 10:14:52,714 - auto_focus.focus - INFO - Focus: 32.11, 1.26, -1.94
2017-02-13 10:14:59,315 - auto_focus.focus - INFO - Focus: 32.31, 0.96, -1.19
2017-02-13 10:15:05,134 - auto_focus.focus - INFO - Focus: 31.81, 1.16, -1.34
2017-02-13 10:15:17,194 - auto_focus.focus - INFO - Focus: 32.11, 1.26, -0.74
2017-02-13 10:15:22,125 - auto_focus.focus - INFO - Focus: 32.11, 1.06, -0.14
2017-02-13 10:15:35,484 - auto_focus.focus - INFO - Focus: 32.11, 1.06, -0.59
2017-02-13 10:41:02,275 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06EE4510>, trait: resolution, old value: 41, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-13 11:01:51,996 - auto_focus.focus - INFO - Focus: 33.82, 12.41, -0.15
2017-02-13 11:11:45,026 - pi3diamond.<module> - INFO - Starting logger.
2017-02-13 11:11:47,006 - emod.start - INFO - Starting Job Manager.
2017-02-13 11:11:47,367 - cron.run - INFO - Starting Cron Daemon.
2017-02-13 14:27:34,591 - auto_focus.focus - INFO - Focus: 27.64, 0.51, -7.81
2017-02-13 14:33:23,792 - emod.submit - INFO - The job <measurements.FRAP.FluorescenceRecoveryAfterPhotobleaching object at 0x170BBA20> is already running or in the queue.
2017-02-13 14:37:51,763 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 41, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 500.0 <type 'float'> was specified.
2017-02-13 14:44:23,924 - auto_focus.focus - INFO - Focus: 40.10, 25.00, -3.34
2017-02-13 14:44:29,253 - auto_focus.focus - INFO - Focus: 40.50, 25.20, -3.79
2017-02-13 14:44:34,803 - auto_focus.focus - INFO - Focus: 40.80, 25.50, -3.79
2017-02-13 15:01:23,914 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 60, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-13 15:02:22,464 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 80, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-13 15:16:19,138 - auto_focus.focus - INFO - Focus: 40.10, 39.60, -4.24
2017-02-13 15:16:22,007 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: y, old value: 40.0, new value: 39.8888888889
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:22,038 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: x, old value: 40.0, new value: 37.0
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:22,048 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: y, old value: 39.8888888889, new value: 36.4444444444
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:23,157 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: x, old value: 39.8, new value: 39.6666666667
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:23,167 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: y, old value: 39.6, new value: 39.4444444444
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:23,267 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: x, old value: 39.6666666667, new value: 38.7777777778
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:23,278 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: y, old value: 39.4444444444, new value: 38.5555555556
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:23,467 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: x, old value: 38.7777777778, new value: 37.7777777778
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 135, in _set_scanner_position
    scanner.setPosition(self.x, self.y, self.z)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 438, in setPosition
    self.setAOLength(1)
  File "D:\pi3diamondnew\hardware\nidaq.py", line 255, in setAOLength
    CHK( dll.DAQmxSetSampTimingType( self.AOTask, DAQmx_Val_OnDemand)  )
  File "D:\pi3diamondnew\hardware\nidaq.py", line 65, in CHK
    raise RuntimeError('nidaq call failed with error %d: %s'%(err,repr(buf.value)))
RuntimeError: nidaq call failed with error -200557: 'Specified property cannot be set while the task is running.\n\nSet the property prior to starting the task, or stop the task prior to setting the property.'
2017-02-13 15:16:23,538 - auto_focus.focus - INFO - Focus: 39.80, 39.60, -4.39
2017-02-13 15:16:30,388 - auto_focus.focus - INFO - Focus: 36.79, 35.99, -3.64
2017-02-13 15:16:34,778 - auto_focus.focus - INFO - Focus: 36.79, 36.09, -3.64
2017-02-13 15:16:40,618 - auto_focus.focus - INFO - Focus: 36.79, 35.99, -2.89
2017-02-13 15:16:45,608 - auto_focus.focus - INFO - Focus: 36.89, 36.09, -2.29
2017-02-13 15:16:50,698 - auto_focus.focus - INFO - Focus: 36.89, 35.89, -2.14
2017-02-13 15:26:37,464 - auto_focus.focus - INFO - Focus: 39.50, 39.50, -2.14
2017-02-13 15:26:44,265 - auto_focus.focus - INFO - Focus: 39.10, 39.00, -1.69
2017-02-13 15:56:18,953 - auto_focus.focus - INFO - Focus: 24.60, 24.70, -0.94
2017-02-13 16:02:00,082 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 201, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 500.0 <type 'float'> was specified.
2017-02-13 16:02:12,903 - auto_focus.focus - INFO - Focus: 34.70, 15.60, -1.84
2017-02-13 16:02:17,622 - auto_focus.focus - INFO - Focus: 34.10, 15.30, -1.09
2017-02-13 16:02:22,743 - auto_focus.focus - INFO - Focus: 34.50, 14.80, -0.34
2017-02-13 16:02:30,352 - auto_focus.focus - INFO - Focus: 34.40, 14.80, 0.41
2017-02-13 16:02:35,223 - auto_focus.focus - INFO - Focus: 34.60, 15.00, 1.16
2017-02-13 16:02:40,053 - auto_focus.focus - INFO - Focus: 34.30, 15.30, 1.76
2017-02-13 16:02:44,894 - auto_focus.focus - INFO - Focus: 33.80, 15.30, 1.76
2017-02-13 16:02:50,134 - auto_focus.focus - INFO - Focus: 33.30, 14.90, 2.51
2017-02-13 16:02:55,493 - auto_focus.focus - INFO - Focus: 32.90, 14.40, 1.91
2017-02-13 16:11:38,799 - auto_focus.focus - INFO - Focus: 42.97, 2.26, 1.91
2017-02-13 16:11:43,630 - auto_focus.focus - INFO - Focus: 42.47, 1.76, 2.66
2017-02-14 12:22:34,792 - auto_focus.focus - INFO - Focus: 26.94, 1.36, 2.49
2017-02-14 12:22:47,132 - auto_focus.focus - INFO - Focus: 27.24, 1.26, 2.04
2017-02-14 12:22:52,023 - auto_focus.focus - INFO - Focus: 27.04, 1.16, 1.89
2017-02-14 12:23:00,112 - auto_focus.focus - INFO - Focus: 27.14, 1.16, 2.19
2017-02-14 12:29:04,947 - auto_focus.focus - INFO - Focus: 24.63, 3.87, 0.60
2017-02-14 12:29:10,357 - auto_focus.focus - INFO - Focus: 24.23, 3.97, 0.60
2017-02-14 12:31:22,766 - auto_focus.focus - INFO - Focus: 35.03, 1.01, 0.45
2017-02-14 12:31:27,776 - auto_focus.focus - INFO - Focus: 35.03, 0.91, 0.45
2017-02-14 12:34:03,526 - auto_focus.focus - INFO - Focus: 37.33, 4.42, -0.30
2017-02-14 12:34:09,607 - auto_focus.focus - INFO - Focus: 37.73, 4.52, -0.60
2017-02-14 12:34:16,137 - auto_focus.focus - INFO - Focus: 38.03, 4.52, -0.30
2017-02-14 13:08:14,976 - auto_focus.focus - INFO - Focus: 24.88, 25.17, 0.75
2017-02-14 13:08:20,776 - auto_focus.focus - INFO - Focus: 24.78, 24.67, 1.50
2017-02-14 13:08:25,655 - auto_focus.focus - INFO - Focus: 24.48, 24.27, 2.10
2017-02-14 13:08:30,815 - auto_focus.focus - INFO - Focus: 24.48, 24.37, 2.25
2017-02-14 13:28:26,535 - utility.stop - WARNING - Thread <StoppableThread(FluorescenceRecoveryAfterPhotobleaching17-02-14_13h27m56, started 3788)> failed to join after 10.0 s. Continuing anyway...
2017-02-14 13:29:02,694 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x06F01510> is already running or in the queue.
2017-02-14 13:30:03,901 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x06F01510> is already running or in the queue.
2017-02-14 13:31:05,104 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x06F01510> is already running or in the queue.
2017-02-14 13:32:06,276 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x06F01510> is already running or in the queue.
2017-02-14 13:33:39,186 - utility.stop - WARNING - Thread <StoppableThread(FluorescenceRecoveryAfterPhotobleaching17-02-14_13h28m42, started 7356)> failed to join after 10.0 s. Continuing anyway...
2017-02-14 13:34:55,335 - auto_focus.focus - INFO - Focus: 30.44, 46.71, 2.78
2017-02-14 13:35:00,966 - auto_focus.focus - INFO - Focus: 30.44, 46.71, 2.63
2017-02-14 13:35:05,885 - auto_focus.focus - INFO - Focus: 30.44, 46.81, 2.78
2017-02-14 13:39:46,095 - auto_focus.focus - INFO - Focus: 38.90, 1.51, 2.18
2017-02-14 13:39:51,016 - auto_focus.focus - INFO - Focus: 38.40, 1.51, 2.18
2017-02-14 13:52:05,055 - utility.stop - WARNING - Thread <StoppableThread(FluorescenceRecoveryAfterPhotobleaching17-02-14_13h48m53, started 7152)> failed to join after 10.0 s. Continuing anyway...
2017-02-14 13:56:00,135 - auto_focus.focus - INFO - Focus: 14.00, 15.40, 2.48
2017-02-14 13:56:04,526 - auto_focus.focus - INFO - Focus: 14.20, 15.10, 1.58
2017-02-14 13:56:10,246 - auto_focus.focus - INFO - Focus: 14.60, 15.10, 0.83
2017-02-14 13:56:17,615 - auto_focus.focus - INFO - Focus: 15.00, 15.30, 1.43
2017-02-14 13:56:28,325 - auto_focus.focus - INFO - Focus: 15.30, 15.30, 1.58
2017-02-14 14:12:39,701 - auto_focus.focus - INFO - Focus: 24.50, 25.00, 2.03
2017-02-14 14:12:44,201 - auto_focus.focus - INFO - Focus: 24.80, 25.00, 2.18
2017-02-14 14:12:51,992 - auto_focus.focus - INFO - Focus: 26.77, 0.23, 1.43
2017-02-14 14:12:56,262 - auto_focus.focus - INFO - Focus: 26.87, 0.40, 0.68
2017-02-14 14:13:00,822 - auto_focus.focus - INFO - Focus: 26.97, 0.40, -0.07
2017-02-14 14:13:05,272 - auto_focus.focus - INFO - Focus: 27.07, 0.20, -0.67
2017-02-14 14:13:09,312 - auto_focus.focus - INFO - Focus: 27.27, 0.20, -1.42
2017-02-14 14:13:13,242 - auto_focus.focus - INFO - Focus: 27.27, 0.00, -2.17
2017-02-14 14:13:16,471 - auto_focus.focus - INFO - Focus: 27.27, 0.10, -2.92
2017-02-14 14:13:20,022 - auto_focus.focus - INFO - Focus: 27.57, 0.00, -3.22
2017-02-14 14:13:28,262 - auto_focus.focus - INFO - Focus: 27.07, 0.30, -3.97
2017-02-14 14:13:32,612 - auto_focus.focus - INFO - Focus: 26.97, 0.70, -4.12
2017-02-14 14:13:37,503 - auto_focus.focus - INFO - Focus: 26.77, 0.80, -4.72
2017-02-14 14:13:46,723 - auto_focus.focus - INFO - Focus: 27.07, 0.90, -5.32
2017-02-14 14:13:51,812 - auto_focus.focus - INFO - Focus: 27.17, 0.90, -5.47
2017-02-14 14:29:27,565 - auto_focus.focus - INFO - Focus: 24.73, 25.20, 4.80
2017-02-14 14:38:39,273 - auto_focus.focus - INFO - Focus: 35.88, 20.75, 4.05
2017-02-14 14:38:44,332 - auto_focus.focus - INFO - Focus: 36.18, 20.85, 3.90
2017-02-14 14:38:49,382 - auto_focus.focus - INFO - Focus: 36.18, 20.85, 3.90
2017-02-14 15:56:32,848 - auto_focus.focus - INFO - Focus: 18.34, 24.70, -2.19
2017-02-14 15:56:37,719 - auto_focus.focus - INFO - Focus: 17.94, 24.60, -1.59
2017-02-14 15:56:44,000 - auto_focus.focus - INFO - Focus: 17.94, 24.60, -1.74
2017-02-14 16:01:17,680 - auto_focus.focus - INFO - Focus: 25.00, 25.10, -2.34
2017-02-14 16:01:22,079 - auto_focus.focus - INFO - Focus: 24.60, 24.70, -1.74
2017-02-14 16:04:54,369 - auto_focus.focus - INFO - Focus: 25.53, 1.76, -7.16
2017-02-14 16:04:59,609 - auto_focus.focus - INFO - Focus: 25.53, 1.26, -7.16
2017-02-14 16:05:04,769 - auto_focus.focus - INFO - Focus: 25.03, 1.56, -7.01
2017-02-14 16:15:00,653 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 201, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 09:21:55,740 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 200, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 500.0 <type 'float'> was specified.
2017-02-15 09:21:55,881 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 2, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 09:32:07,082 - auto_focus.focus - INFO - Focus: 14.94, 14.27, -0.09
2017-02-15 09:32:11,961 - auto_focus.focus - INFO - Focus: 14.44, 14.47, 0.66
2017-02-15 09:32:16,651 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BC2E210> is already running or in the queue.
2017-02-15 09:32:16,911 - auto_focus.focus - INFO - Focus: 13.94, 14.77, 1.41
2017-02-15 09:32:22,381 - auto_focus.focus - INFO - Focus: 13.84, 15.17, 1.56
2017-02-15 09:32:32,082 - auto_focus.focus - INFO - Focus: 13.54, 15.07, 1.86
2017-02-15 09:32:37,151 - auto_focus.focus - INFO - Focus: 13.54, 14.57, 2.31
2017-02-15 09:32:42,482 - auto_focus.focus - INFO - Focus: 13.94, 14.67, 2.01
2017-02-15 09:39:06,025 - auto_focus.focus - INFO - Focus: 34.50, 25.00, -16.61
2017-02-15 09:39:11,025 - auto_focus.focus - INFO - Focus: 34.40, 24.90, -16.46
2017-02-15 09:44:14,005 - auto_focus.focus - INFO - Focus: 30.94, 6.00, -1.02
2017-02-15 09:44:22,275 - auto_focus.focus - INFO - Focus: 30.94, 6.30, -1.47
2017-02-15 09:44:27,305 - auto_focus.focus - INFO - Focus: 30.44, 5.80, -1.02
2017-02-15 09:44:32,474 - auto_focus.focus - INFO - Focus: 30.74, 5.30, -0.87
2017-02-15 09:48:38,859 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 150, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 500.0 <type 'float'> was specified.
2017-02-15 09:51:15,082 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 201, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-15 09:58:45,604 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 151, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 09:59:48,559 - auto_focus.focus - INFO - Focus: 31.40, 15.90, -1.02
2017-02-15 09:59:53,888 - auto_focus.focus - INFO - Focus: 31.80, 16.10, -0.87
2017-02-15 10:00:35,269 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 201, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 10:02:45,499 - auto_focus.focus - INFO - Focus: 28.01, 15.33, -1.02
2017-02-15 10:05:57,759 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: thresh_high, old value: 1000.0, new value: 200\
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\spotfinderv3.py", line 374, in redraw_image
    self.scan_plot.value_range.high_setting=self.confocal.thresh_high
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2094, in validate
    return self.slow_validate( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2102, in slow_validate
    self.error( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'high_setting' trait of a DataRange1D instance must be a float or 'auto' or 'track', but a value of u'200\\' <type 'unicode'> was specified.
2017-02-15 10:05:57,809 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: thresh_high, old value: 1000.0, new value: 200\
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\goodspot.py", line 168, in redraw_image
    self.scan_plot.value_range.high_setting=self.confocal.thresh_high
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2094, in validate
    return self.slow_validate( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2102, in slow_validate
    self.error( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'high_setting' trait of a DataRange1D instance must be a float or 'auto' or 'track', but a value of u'200\\' <type 'unicode'> was specified.
2017-02-15 10:06:10,459 - auto_focus.focus - INFO - Focus: 36.28, 25.17, -0.27
2017-02-15 10:06:15,759 - auto_focus.focus - INFO - Focus: 36.48, 24.67, -0.87
2017-02-15 10:08:09,928 - auto_focus.focus - INFO - Focus: 26.08, 22.66, -1.47
2017-02-15 10:08:21,219 - auto_focus.focus - INFO - Focus: 34.93, 16.94, -0.27
2017-02-15 10:08:26,408 - auto_focus.focus - INFO - Focus: 34.43, 16.44, 0.48
2017-02-15 10:08:31,309 - auto_focus.focus - INFO - Focus: 34.13, 16.74, 1.08
2017-02-15 10:08:36,229 - auto_focus.focus - INFO - Focus: 34.03, 17.04, 1.83
2017-02-15 10:15:45,460 - auto_focus.focus - INFO - Focus: 13.07, 25.40, -0.12
2017-02-15 10:15:50,296 - auto_focus.focus - INFO - Focus: 12.57, 25.80, -0.87
2017-02-15 10:15:55,301 - auto_focus.focus - INFO - Focus: 12.77, 26.00, -1.02
2017-02-15 10:16:00,269 - auto_focus.focus - INFO - Focus: 12.87, 26.00, -0.57
2017-02-15 10:16:05,630 - auto_focus.focus - INFO - Focus: 12.77, 26.40, -0.27
2017-02-15 10:17:18,907 - auto_focus.focus - INFO - Focus: 19.95, 16.43, 0.48
2017-02-15 10:17:23,767 - auto_focus.focus - INFO - Focus: 19.75, 16.53, 1.23
2017-02-15 10:17:28,657 - auto_focus.focus - INFO - Focus: 19.25, 16.53, 1.98
2017-02-15 10:17:33,538 - auto_focus.focus - INFO - Focus: 18.75, 16.33, 2.73
2017-02-15 10:17:38,558 - auto_focus.focus - INFO - Focus: 18.55, 16.23, 3.48
2017-02-15 10:17:43,558 - auto_focus.focus - INFO - Focus: 18.35, 15.73, 4.23
2017-02-15 10:17:48,538 - auto_focus.focus - INFO - Focus: 17.95, 16.03, 4.38
2017-02-15 10:17:59,828 - auto_focus.focus - INFO - Focus: 18.35, 16.43, 4.53
2017-02-15 10:26:06,279 - auto_focus.focus - INFO - Focus: 25.58, 13.22, 1.73
2017-02-15 10:26:11,209 - auto_focus.focus - INFO - Focus: 25.48, 13.22, 1.58
2017-02-15 10:26:16,378 - auto_focus.focus - INFO - Focus: 25.48, 13.32, 1.73
2017-02-15 10:30:21,032 - auto_focus.focus - INFO - Focus: 11.31, 4.88, 1.73
2017-02-15 10:30:25,903 - auto_focus.focus - INFO - Focus: 11.21, 4.78, 2.03
2017-02-15 10:32:48,543 - auto_focus.focus - INFO - Focus: 30.35, 20.15, 2.18
2017-02-15 10:33:57,864 - auto_focus.focus - INFO - Focus: 29.85, 19.65, 1.43
2017-02-15 10:34:08,813 - auto_focus.undo - INFO - Can undo only once.
2017-02-15 10:36:05,743 - auto_focus.focus - INFO - Focus: 26.13, 18.60, 1.43
2017-02-15 10:36:10,763 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BC2E210> is already running or in the queue.
2017-02-15 10:36:11,293 - auto_focus.focus - INFO - Focus: 25.63, 18.10, 0.68
2017-02-15 10:36:15,864 - auto_focus.focus - INFO - Focus: 25.13, 17.60, -0.07
2017-02-15 10:37:17,713 - auto_focus.focus - INFO - Focus: 15.83, 9.80, -0.07
2017-02-15 10:37:22,523 - auto_focus.focus - INFO - Focus: 15.33, 9.30, -0.67
2017-02-15 10:37:26,844 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BC2E210> is already running or in the queue.
2017-02-15 10:37:27,414 - auto_focus.focus - INFO - Focus: 14.83, 8.80, -1.42
2017-02-15 10:37:31,624 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BC2E210> is already running or in the queue.
2017-02-15 10:37:32,164 - auto_focus.focus - INFO - Focus: 14.33, 8.30, -1.42
2017-02-15 10:37:36,914 - auto_focus.focus - INFO - Focus: 13.83, 7.80, -1.57
2017-02-15 10:40:24,003 - auto_focus.focus - INFO - Focus: 24.50, 24.50, -0.97
2017-02-15 10:40:28,874 - auto_focus.focus - INFO - Focus: 24.00, 24.00, -1.27
2017-02-15 10:40:33,723 - auto_focus.focus - INFO - Focus: 23.50, 23.50, -1.27
2017-02-15 10:45:55,418 - auto_focus.focus - INFO - Focus: 24.50, 24.50, -1.27
2017-02-15 10:52:52,930 - auto_focus.focus - INFO - Focus: 25.31, 19.52, -0.52
2017-02-15 10:52:57,819 - auto_focus.focus - INFO - Focus: 25.71, 19.72, -0.22
2017-02-15 10:53:02,730 - auto_focus.focus - INFO - Focus: 25.61, 20.12, -0.07
2017-02-15 10:53:07,230 - auto_focus.focus - INFO - Focus: 25.91, 20.02, 0.23
2017-02-15 10:56:51,609 - auto_focus.focus - INFO - Focus: 15.33, 24.88, 0.23
2017-02-15 10:56:56,500 - auto_focus.focus - INFO - Focus: 14.83, 24.38, 0.23
2017-02-15 10:57:01,680 - auto_focus.focus - INFO - Focus: 14.33, 23.88, 0.23
2017-02-15 10:57:11,710 - auto_focus.focus - INFO - Focus: 11.31, 25.13, 0.23
2017-02-15 10:57:16,529 - auto_focus.focus - INFO - Focus: 10.81, 24.63, 0.23
2017-02-15 10:57:21,369 - auto_focus.focus - INFO - Focus: 10.31, 24.13, -0.37
2017-02-15 10:57:26,220 - auto_focus.focus - INFO - Focus: 9.81, 23.63, -0.37
2017-02-15 10:58:19,490 - auto_focus.focus - INFO - Focus: 16.08, 25.33, 0.60
2017-02-15 11:00:19,401 - auto_focus.focus - INFO - Focus: 20.86, 25.53, 0.45
2017-02-15 11:00:24,290 - auto_focus.focus - INFO - Focus: 20.66, 25.83, 0.45
2017-02-15 11:00:29,240 - auto_focus.focus - INFO - Focus: 20.56, 25.33, 0.30
2017-02-15 11:00:37,990 - auto_focus.focus - INFO - Focus: 40.00, 29.90, 0.30
2017-02-15 11:00:42,770 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0BC2E210> is already running or in the queue.
2017-02-15 11:00:42,891 - auto_focus.focus - INFO - Focus: 40.10, 29.40, -0.15
2017-02-15 11:00:48,200 - auto_focus.focus - INFO - Focus: 39.60, 28.90, -0.30
2017-02-15 11:00:54,040 - auto_focus.focus - INFO - Focus: 39.10, 28.40, -1.05
2017-02-15 11:01:05,891 - auto_focus.focus - INFO - Focus: 20.75, 31.36, -0.30
2017-02-15 11:01:10,891 - auto_focus.focus - INFO - Focus: 20.55, 30.96, -0.60
2017-02-15 11:01:15,851 - auto_focus.focus - INFO - Focus: 20.05, 30.46, -1.05
2017-02-15 11:01:20,750 - auto_focus.focus - INFO - Focus: 19.55, 29.96, -0.90
2017-02-15 11:48:01,107 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 151, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 11:48:24,107 - auto_focus.focus - INFO - Focus: 18.85, 2.36, -0.15
2017-02-15 11:48:28,976 - auto_focus.focus - INFO - Focus: 18.75, 2.16, 0.30
2017-02-15 11:48:34,026 - auto_focus.focus - INFO - Focus: 19.05, 2.56, 0.45
2017-02-15 11:48:40,467 - auto_focus.focus - INFO - Focus: 19.25, 2.56, 0.75
2017-02-15 11:55:06,884 - auto_focus.focus - INFO - Focus: 17.09, 17.49, 0.90
2017-02-15 11:55:13,575 - auto_focus.focus - INFO - Focus: 16.59, 17.89, 1.35
2017-02-15 11:55:22,194 - auto_focus.focus - INFO - Focus: 13.01, 11.96, 1.35
2017-02-15 11:55:27,065 - auto_focus.focus - INFO - Focus: 13.01, 11.86, 1.50
2017-02-15 12:15:25,846 - auto_focus.focus - INFO - Focus: 12.71, 12.06, 1.50
2017-02-15 12:15:31,387 - auto_focus.focus - INFO - Focus: 12.91, 12.16, 1.35
2017-02-15 12:45:59,092 - auto_focus.focus - INFO - Focus: 33.31, 6.83, 1.65
2017-02-15 12:47:28,951 - auto_focus.focus - INFO - Focus: 0.51, 6.03, -18.71
2017-02-15 12:47:34,153 - auto_focus.focus - INFO - Focus: 0.11, 6.03, -19.31
2017-02-15 12:47:38,362 - auto_focus.focus - INFO - Focus: 0.00, 5.53, -20.06
2017-02-15 12:47:41,852 - auto_focus.focus - INFO - Focus: 0.00, 5.03, -20.36
2017-02-15 12:49:04,233 - auto_focus.focus - INFO - Focus: 24.90, 24.50, -20.81
2017-02-15 12:49:09,131 - auto_focus.focus - INFO - Focus: 24.50, 24.00, -21.41
2017-02-15 12:49:13,529 - auto_focus.focus - INFO - Focus: 24.50, 24.60, -20.51
2017-02-15 12:58:13,729 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 200, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 13:08:09,236 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 151, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 500.0 <type 'float'> was specified.
2017-02-15 13:11:06,846 - auto_focus.focus - INFO - Focus: 20.40, 34.20, -17.25
2017-02-15 13:13:33,217 - auto_focus.focus - INFO - Focus: 25.00, 25.40, -16.50
2017-02-15 13:13:42,826 - auto_focus.focus - INFO - Focus: 10.45, 22.81, -17.25
2017-02-15 13:13:48,107 - auto_focus.focus - INFO - Focus: 10.15, 22.41, -17.40
2017-02-15 13:16:23,331 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 200, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 13:16:38,736 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 151, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 13:22:37,721 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 121, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-15 13:44:19,369 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 101, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-15 13:45:26,710 - auto_focus.focus - INFO - Focus: 24.77, 26.78, -16.95
2017-02-15 13:45:31,760 - auto_focus.focus - INFO - Focus: 24.97, 26.28, -16.95
2017-02-15 13:49:48,371 - auto_focus.focus - INFO - Focus: 25.63, 14.02, -16.95
2017-02-15 14:00:09,920 - auto_focus.focus - INFO - Focus: 24.50, 14.70, -16.95
2017-02-15 14:05:47,071 - auto_focus.focus - INFO - Focus: 24.50, 15.20, -16.95
2017-02-15 14:33:48,072 - auto_focus.focus - INFO - Focus: 28.10, 23.14, -16.95
2017-02-15 14:40:30,269 - auto_focus.focus - INFO - Focus: 44.37, 21.86, -16.20
2017-02-15 14:40:40,099 - auto_focus.focus - INFO - Focus: 46.58, 29.75, -16.95
2017-02-15 14:40:45,140 - auto_focus.focus - INFO - Focus: 46.98, 29.25, -17.55
2017-02-15 14:40:50,089 - auto_focus.focus - INFO - Focus: 47.28, 28.85, -17.55
2017-02-15 14:40:54,839 - auto_focus.focus - INFO - Focus: 47.38, 28.35, -17.55
2017-02-15 14:45:15,460 - auto_focus.focus - INFO - Focus: 39.20, 26.13, -17.55
2017-02-15 14:45:37,750 - auto_focus.focus - INFO - Focus: 40.20, 20.15, -17.55
2017-02-15 14:56:30,331 - auto_focus.focus - INFO - Focus: 40.01, 18.73, -17.55
2017-02-15 14:57:51,230 - auto_focus.focus - INFO - Focus: 33.10, 24.09, -17.55
2017-02-15 14:59:33,740 - auto_focus.focus - INFO - Focus: 35.30, 22.20, -17.70
2017-02-15 15:03:22,742 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 101, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 500.0 <type 'float'> was specified.
2017-02-15 15:12:20,691 - auto_focus.focus - INFO - Focus: 22.71, 24.60, 0.23
2017-02-15 15:12:25,601 - auto_focus.focus - INFO - Focus: 22.71, 24.60, 0.23
2017-02-15 15:26:07,678 - auto_focus.focus - INFO - Focus: 26.64, 21.51, -5.41
2017-02-15 15:26:12,519 - auto_focus.focus - INFO - Focus: 26.54, 21.91, -4.66
2017-02-15 15:26:17,388 - auto_focus.focus - INFO - Focus: 26.24, 21.81, -3.91
2017-02-15 15:26:22,618 - auto_focus.focus - INFO - Focus: 25.74, 22.11, -3.16
2017-02-15 15:26:34,588 - auto_focus.focus - INFO - Focus: 26.94, 20.71, -2.41
2017-02-15 15:26:39,948 - auto_focus.focus - INFO - Focus: 27.34, 20.51, -1.81
2017-02-15 15:26:44,858 - auto_focus.focus - INFO - Focus: 27.74, 20.91, -1.06
2017-02-15 15:26:49,828 - auto_focus.focus - INFO - Focus: 27.54, 21.21, -0.46
2017-02-16 09:18:53,160 - auto_focus.focus - INFO - Focus: 25.23, 24.50, -5.76
2017-02-16 09:18:58,259 - auto_focus.focus - INFO - Focus: 25.63, 24.00, -5.01
2017-02-16 09:19:03,279 - auto_focus.focus - INFO - Focus: 25.63, 23.60, -4.71
2017-02-16 09:19:08,460 - auto_focus.focus - INFO - Focus: 25.33, 23.20, -4.86
2017-02-16 09:31:22,326 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: thresh_high, old value: 300.0, new value: 300z
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\spotfinderv3.py", line 374, in redraw_image
    self.scan_plot.value_range.high_setting=self.confocal.thresh_high
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2094, in validate
    return self.slow_validate( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2102, in slow_validate
    self.error( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'high_setting' trait of a DataRange1D instance must be a float or 'auto' or 'track', but a value of u'300z' <type 'unicode'> was specified.
2017-02-16 09:31:22,346 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: thresh_high, old value: 300.0, new value: 300z
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\goodspot.py", line 168, in redraw_image
    self.scan_plot.value_range.high_setting=self.confocal.thresh_high
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2094, in validate
    return self.slow_validate( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 2102, in slow_validate
    self.error( object, name, value )
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'high_setting' trait of a DataRange1D instance must be a float or 'auto' or 'track', but a value of u'300z' <type 'unicode'> was specified.
2017-02-16 09:31:43,137 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x06F01510>, trait: resolution, old value: 200, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-16 09:36:34,526 - auto_focus.focus - INFO - Focus: 13.40, 13.90, -5.61
2017-02-16 09:36:39,607 - auto_focus.focus - INFO - Focus: 12.90, 14.30, -6.36
2017-02-16 09:36:44,526 - auto_focus.focus - INFO - Focus: 12.50, 14.10, -6.96
2017-02-16 09:36:49,437 - auto_focus.focus - INFO - Focus: 12.20, 13.60, -7.56
2017-02-16 09:36:54,336 - auto_focus.focus - INFO - Focus: 12.40, 13.40, -7.56
2017-02-16 09:37:04,316 - auto_focus.focus - INFO - Focus: 35.18, 1.41, -8.16
2017-02-16 09:37:09,707 - auto_focus.focus - INFO - Focus: 34.78, 0.91, -8.91
2017-02-16 09:37:14,647 - auto_focus.focus - INFO - Focus: 34.28, 0.41, -9.21
2017-02-16 09:37:19,836 - auto_focus.focus - INFO - Focus: 33.78, 0.20, -9.36
2017-02-16 09:45:52,769 - auto_focus.focus - INFO - Focus: 42.21, 21.36, -10.11
2017-02-16 09:45:57,779 - auto_focus.focus - INFO - Focus: 42.61, 20.86, -10.86
2017-02-16 09:46:02,740 - auto_focus.focus - INFO - Focus: 42.21, 20.36, -11.31
2017-02-16 09:46:07,819 - auto_focus.focus - INFO - Focus: 42.61, 19.96, -11.76
2017-02-16 09:49:44,809 - auto_focus.focus - INFO - Focus: 11.51, 2.36, -11.16
2017-02-16 09:49:49,789 - auto_focus.focus - INFO - Focus: 11.01, 1.86, -10.56
2017-02-16 09:49:54,839 - auto_focus.focus - INFO - Focus: 11.41, 1.46, -9.81
2017-02-16 09:49:59,779 - auto_focus.focus - INFO - Focus: 10.91, 0.96, -9.51
2017-02-16 09:50:04,950 - auto_focus.focus - INFO - Focus: 11.31, 0.46, -9.36
2017-02-16 09:59:52,635 - auto_focus.focus - INFO - Focus: 39.50, 2.06, -9.81
2017-02-16 09:59:57,585 - auto_focus.focus - INFO - Focus: 39.10, 1.56, -9.51
2017-02-16 10:04:20,973 - auto_focus.focus - INFO - Focus: 29.15, 29.25, -9.66
2017-02-16 10:04:25,884 - auto_focus.focus - INFO - Focus: 29.25, 29.35, -10.11
2017-02-16 10:04:31,404 - auto_focus.focus - INFO - Focus: 29.05, 29.35, -9.81
2017-02-16 10:10:38,875 - auto_focus.focus - INFO - Focus: 25.13, 17.54, -9.21
2017-02-16 10:10:43,884 - auto_focus.focus - INFO - Focus: 25.13, 17.34, -8.61
2017-02-16 10:10:48,904 - auto_focus.focus - INFO - Focus: 25.03, 17.64, -7.86
2017-02-16 10:10:53,805 - auto_focus.focus - INFO - Focus: 24.63, 17.14, -8.16
2017-02-16 10:15:29,693 - auto_focus.focus - INFO - Focus: 24.13, 17.04, -7.41
2017-02-16 10:15:35,463 - auto_focus.focus - INFO - Focus: 23.93, 16.64, -6.81
2017-02-16 10:15:40,433 - auto_focus.focus - INFO - Focus: 24.33, 16.84, -7.56
2017-02-16 10:15:45,372 - auto_focus.focus - INFO - Focus: 23.83, 17.24, -7.41
2017-02-16 10:15:50,263 - auto_focus.focus - INFO - Focus: 23.53, 17.24, -7.11
2017-02-16 10:26:54,069 - auto_focus.focus - INFO - Focus: 10.20, 20.65, -6.36
2017-02-16 10:27:01,668 - auto_focus.focus - INFO - Focus: 10.60, 20.45, -6.66
2017-02-16 10:27:06,779 - auto_focus.focus - INFO - Focus: 10.90, 20.55, -6.06
2017-02-16 10:27:11,969 - auto_focus.focus - INFO - Focus: 10.60, 20.45, -5.31
2017-02-16 10:27:17,279 - auto_focus.focus - INFO - Focus: 10.90, 20.15, -4.71
2017-02-16 10:47:54,174 - auto_focus.focus - INFO - Focus: 23.01, 19.65, 5.85
2017-02-16 10:48:00,983 - auto_focus.focus - INFO - Focus: 23.41, 19.85, 5.40
2017-02-16 10:48:26,114 - auto_focus.focus - INFO - Focus: 14.58, 1.01, 5.90
2017-02-16 10:48:31,094 - auto_focus.focus - INFO - Focus: 14.08, 0.51, 6.05
2017-02-16 10:48:36,104 - auto_focus.focus - INFO - Focus: 13.58, 0.21, 6.65
2017-02-16 10:48:50,733 - auto_focus.focus - INFO - Focus: 34.02, 2.01, 6.05
2017-02-16 10:48:55,874 - auto_focus.focus - INFO - Focus: 33.52, 2.01, 5.60
2017-02-16 10:50:38,783 - auto_focus.focus - INFO - Focus: 35.58, 17.59, 5.90
2017-02-16 10:50:43,664 - auto_focus.focus - INFO - Focus: 35.28, 17.69, 6.65
2017-02-16 10:50:50,253 - auto_focus.focus - INFO - Focus: 34.78, 17.29, 6.35
2017-02-16 10:53:21,243 - auto_focus.focus - INFO - Focus: 30.40, 17.44, 6.80
2017-02-16 10:53:26,203 - auto_focus.focus - INFO - Focus: 30.80, 17.84, 6.20
2017-02-16 11:05:41,918 - auto_focus.focus - INFO - Focus: 31.76, 18.14, -3.14
2017-02-16 11:05:46,789 - auto_focus.focus - INFO - Focus: 31.36, 18.54, -2.54
2017-02-16 11:05:51,749 - auto_focus.focus - INFO - Focus: 30.96, 18.14, -1.79
2017-02-16 11:05:56,739 - auto_focus.focus - INFO - Focus: 31.36, 18.54, -1.19
2017-02-16 11:06:01,908 - auto_focus.focus - INFO - Focus: 31.36, 18.34, -0.44
2017-02-16 11:06:06,799 - auto_focus.focus - INFO - Focus: 31.66, 17.84, -0.29
2017-02-16 11:09:01,928 - auto_focus.focus - INFO - Focus: 24.52, 5.48, -0.44
2017-02-16 11:09:06,789 - auto_focus.focus - INFO - Focus: 24.92, 5.08, 0.31
2017-02-16 11:09:11,989 - auto_focus.focus - INFO - Focus: 24.42, 4.58, 0.16
2017-02-16 11:09:16,888 - auto_focus.focus - INFO - Focus: 24.02, 4.08, -0.14
2017-02-16 11:10:07,390 - auto_focus.focus - INFO - Focus: 25.02, 5.28, -0.74
2017-02-16 11:10:12,309 - auto_focus.focus - INFO - Focus: 25.12, 4.88, 0.01
2017-02-16 11:10:17,349 - auto_focus.focus - INFO - Focus: 24.82, 4.48, -0.74
2017-02-16 12:16:29,407 - auto_focus.focus - INFO - Focus: 43.57, 4.38, -4.90
2017-02-16 12:16:34,313 - auto_focus.focus - INFO - Focus: 43.87, 3.88, -4.15
2017-02-16 12:16:39,209 - auto_focus.focus - INFO - Focus: 44.07, 3.58, -3.55
2017-02-16 12:16:44,108 - auto_focus.focus - INFO - Focus: 43.77, 3.28, -3.85
2017-02-16 12:19:02,102 - auto_focus.focus - INFO - Focus: 22.72, 9.65, -3.25
2017-02-16 12:19:07,035 - auto_focus.focus - INFO - Focus: 22.72, 9.35, -3.40
2017-02-16 12:19:28,220 - auto_focus.focus - INFO - Focus: 6.28, 12.96, -2.65
2017-02-16 12:19:33,344 - auto_focus.focus - INFO - Focus: 5.88, 12.46, -3.25
2017-02-16 12:19:38,618 - auto_focus.focus - INFO - Focus: 6.18, 11.96, -2.95
2017-02-16 12:22:40,128 - auto_focus.focus - INFO - Focus: 8.29, 7.54, -2.50
2017-02-16 12:22:45,148 - auto_focus.focus - INFO - Focus: 8.69, 7.54, -1.90
2017-02-16 12:22:50,209 - auto_focus.focus - INFO - Focus: 8.49, 7.84, -1.90
2017-02-16 12:43:50,558 - auto_focus.focus - INFO - Focus: 30.27, 7.06, -2.35
2017-02-16 12:52:12,463 - auto_focus.focus - INFO - Focus: 43.38, 9.70, -1.90
2017-02-16 12:52:18,703 - auto_focus.focus - INFO - Focus: 42.88, 9.80, -2.05
2017-02-16 13:00:57,367 - auto_focus.focus - INFO - Focus: 46.39, 10.27, -2.30
2017-02-16 13:01:02,282 - auto_focus.focus - INFO - Focus: 46.29, 10.07, -2.30
2017-02-16 13:01:07,305 - auto_focus.focus - INFO - Focus: 46.29, 9.67, -2.60
2017-02-16 13:01:14,926 - auto_focus.focus - INFO - Focus: 46.19, 9.57, -1.85
2017-02-16 13:01:19,869 - auto_focus.focus - INFO - Focus: 45.89, 9.07, -1.40
2017-02-16 13:01:29,630 - auto_focus.focus - INFO - Focus: 28.16, 11.87, -1.70
2017-02-16 13:06:51,960 - auto_focus.focus - INFO - Focus: 4.02, 11.46, -2.15
2017-02-16 13:06:56,349 - auto_focus.focus - INFO - Focus: 4.82, 11.16, -1.55
2017-02-16 13:08:18,430 - auto_focus.focus - INFO - Focus: 23.62, 1.01, -2.30
2017-02-16 13:08:23,359 - auto_focus.focus - INFO - Focus: 23.12, 1.41, -2.90
2017-02-16 13:08:28,230 - auto_focus.focus - INFO - Focus: 22.92, 1.11, -2.15
2017-02-16 13:08:33,329 - auto_focus.focus - INFO - Focus: 22.52, 1.51, -2.00
2017-02-16 13:18:41,101 - auto_focus.focus - INFO - Focus: 29.60, 3.62, 2.18
2017-02-16 13:19:33,801 - auto_focus.focus - INFO - Focus: 34.07, 5.78, 2.63
2017-02-16 13:19:38,760 - auto_focus.focus - INFO - Focus: 33.67, 5.88, 2.78
2017-02-16 13:19:44,121 - auto_focus.focus - INFO - Focus: 33.17, 5.48, 2.78
2017-02-16 13:22:22,421 - auto_focus.focus - INFO - Focus: 24.12, 21.00, 3.32
2017-02-16 13:22:27,220 - auto_focus.focus - INFO - Focus: 23.72, 21.20, 3.02
2017-02-16 13:22:32,101 - auto_focus.focus - INFO - Focus: 23.32, 21.60, 2.72
2017-02-16 13:22:36,911 - auto_focus.focus - INFO - Focus: 22.92, 21.80, 2.42
2017-02-16 13:22:41,780 - auto_focus.focus - INFO - Focus: 22.72, 21.50, 2.42
2017-02-16 13:25:44,131 - auto_focus.focus - INFO - Focus: 27.24, 5.53, 3.17
2017-02-16 13:25:49,181 - auto_focus.focus - INFO - Focus: 27.64, 5.03, 3.17
2017-02-16 13:28:08,221 - auto_focus.focus - INFO - Focus: 28.49, 22.51, 3.02
2017-02-16 13:28:12,982 - auto_focus.focus - INFO - Focus: 27.99, 22.91, 3.32
2017-02-16 13:28:17,792 - auto_focus.focus - INFO - Focus: 27.69, 22.81, 3.62
2017-02-16 13:31:15,046 - auto_focus.focus - INFO - Focus: 29.60, 23.06, 3.02
2017-02-16 13:31:20,599 - auto_focus.focus - INFO - Focus: 29.10, 23.46, 2.87
2017-02-16 13:44:07,267 - auto_focus.focus - INFO - Focus: 29.05, 25.44, 3.62
2017-02-16 13:47:09,487 - auto_focus.focus - INFO - Focus: 35.14, 7.75, 3.77
2017-02-16 13:50:14,967 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.tools.cursor_tool.CursorTool2D object at 0x06F3F1E0>, trait: current_index, old value: (280, 62), new value: (280, 31)
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 476, in call_0
    self.dispatch( self.handler )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1374, in wrapper0
    return function(arg)
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 3693, in notify
    self.trait_property_changed( name, old )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1304, in decorator
    self.__dict__[ name ] = result = function( self )
  File "C:\Pythonepd\lib\site-packages\chaco\tools\cursor_tool.py", line 235, in _get_current_position
    x = xdata.get_data()[ndx]
IndexError: index out of bounds
2017-02-16 13:50:15,038 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.tools.cursor_tool.CursorTool2D object at 0x06F3F1E0>, trait: current_index, old value: (280, 31), new value: (280, 35)
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 476, in call_0
    self.dispatch( self.handler )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1374, in wrapper0
    return function(arg)
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 3693, in notify
    self.trait_property_changed( name, old )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1304, in decorator
    self.__dict__[ name ] = result = function( self )
  File "C:\Pythonepd\lib\site-packages\chaco\tools\cursor_tool.py", line 235, in _get_current_position
    x = xdata.get_data()[ndx]
IndexError: index out of bounds
2017-02-16 13:50:15,048 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.tools.cursor_tool.CursorTool2D object at 0x06F3F1E0>, trait: current_index, old value: (280, 35), new value: (280, 36)
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 476, in call_0
    self.dispatch( self.handler )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1374, in wrapper0
    return function(arg)
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 3693, in notify
    self.trait_property_changed( name, old )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1304, in decorator
    self.__dict__[ name ] = result = function( self )
  File "C:\Pythonepd\lib\site-packages\chaco\tools\cursor_tool.py", line 235, in _get_current_position
    x = xdata.get_data()[ndx]
IndexError: index out of bounds
2017-02-16 13:50:15,187 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.tools.cursor_tool.CursorTool2D object at 0x06F3F1E0>, trait: current_index, old value: (280, 36), new value: (280, 43)
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 476, in call_0
    self.dispatch( self.handler )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1374, in wrapper0
    return function(arg)
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 3693, in notify
    self.trait_property_changed( name, old )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1304, in decorator
    self.__dict__[ name ] = result = function( self )
  File "C:\Pythonepd\lib\site-packages\chaco\tools\cursor_tool.py", line 235, in _get_current_position
    x = xdata.get_data()[ndx]
IndexError: index out of bounds
2017-02-16 13:50:15,358 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <chaco.tools.cursor_tool.CursorTool2D object at 0x06F3F1E0>, trait: current_index, old value: (280, 43), new value: (280, 47)
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 476, in call_0
    self.dispatch( self.handler )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 454, in dispatch
    handler( *args )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1374, in wrapper0
    return function(arg)
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 3693, in notify
    self.trait_property_changed( name, old )
  File "C:\Pythonepd\lib\site-packages\traits\has_traits.py", line 1304, in decorator
    self.__dict__[ name ] = result = function( self )
  File "C:\Pythonepd\lib\site-packages\chaco\tools\cursor_tool.py", line 235, in _get_current_position
    x = xdata.get_data()[ndx]
IndexError: index out of bounds
2017-02-16 13:51:11,348 - pi3diamond.<module> - INFO - Starting logger.
2017-02-16 13:51:20,628 - emod.start - INFO - Starting Job Manager.
2017-02-16 13:51:20,657 - cron.run - INFO - Starting Cron Daemon.
2017-02-16 13:56:10,469 - auto_focus.focus - INFO - Focus: 31.91, 11.81, 3.77
2017-02-16 13:56:14,848 - auto_focus.focus - INFO - Focus: 31.91, 11.81, 3.77
2017-02-16 13:56:25,479 - auto_focus.focus - INFO - Focus: 32.01, 11.71, 3.92
2017-02-16 13:56:30,948 - auto_focus.focus - INFO - Focus: 32.11, 11.31, 4.22
2017-02-16 14:42:45,154 - auto_focus.focus - INFO - Focus: 36.28, 1.21, 3.94
2017-02-16 14:45:10,224 - auto_focus.focus - INFO - Focus: 26.33, 34.72, 3.79
2017-02-16 14:48:44,934 - auto_focus.focus - INFO - Focus: 20.40, 35.12, 5.60
2017-02-16 14:48:50,384 - auto_focus.focus - INFO - Focus: 19.90, 35.52, 6.05
2017-02-16 14:58:19,894 - auto_focus.focus - INFO - Focus: 26.23, 35.02, 0.47
2017-02-16 15:03:52,471 - auto_focus.focus - INFO - Focus: 30.40, 4.17, 1.22
2017-02-16 15:03:57,532 - auto_focus.focus - INFO - Focus: 29.90, 4.07, 0.47
2017-02-16 18:18:12,457 - auto_focus.focus - INFO - Focus: 24.26, 25.00, 1.85
2017-02-16 18:18:21,858 - auto_focus.focus - INFO - Focus: 24.36, 25.10, 1.85
2017-02-16 18:18:26,888 - auto_focus.focus - INFO - Focus: 24.36, 25.10, 1.85
2017-02-16 18:18:38,747 - auto_focus.focus - INFO - Focus: 24.26, 25.10, 1.85
2017-02-16 18:18:44,667 - auto_focus.focus - INFO - Focus: 24.26, 25.10, 1.55
2017-02-16 18:19:59,641 - auto_focus.focus - INFO - Focus: 37.73, 11.61, 1.55
2017-02-16 18:20:05,911 - auto_focus.focus - INFO - Focus: 37.63, 12.01, 1.40
2017-02-16 18:20:13,572 - auto_focus.focus - INFO - Focus: 37.63, 12.21, 1.55
2017-02-16 18:21:58,223 - auto_focus.focus - INFO - Focus: 35.28, 10.23, 1.40
2017-02-16 18:22:08,713 - auto_focus.focus - INFO - Focus: 35.28, 10.23, 1.25
2017-02-16 18:22:14,493 - auto_focus.focus - INFO - Focus: 35.28, 10.23, 1.40
2017-02-16 18:22:20,342 - auto_focus.focus - INFO - Focus: 35.28, 10.23, 1.40
2017-02-16 18:34:06,084 - auto_focus.focus - INFO - Focus: 28.54, 25.20, 0.93
2017-02-16 18:35:05,874 - auto_focus.focus - INFO - Focus: 37.99, 12.11, 1.08
2017-02-16 18:35:11,203 - auto_focus.focus - INFO - Focus: 37.99, 12.11, 1.08
2017-02-17 10:15:51,734 - auto_focus.focus - INFO - Focus: 34.06, 7.89, -4.45
2017-02-17 10:15:57,275 - auto_focus.focus - INFO - Focus: 33.56, 7.39, -4.45
2017-02-17 10:16:02,634 - auto_focus.focus - INFO - Focus: 33.96, 6.89, -4.75
2017-02-17 10:16:08,194 - auto_focus.focus - INFO - Focus: 33.46, 6.39, -4.75
2017-02-17 10:18:31,115 - auto_focus.focus - INFO - Focus: 32.96, 5.89, -4.75
2017-02-17 10:18:36,394 - auto_focus.focus - INFO - Focus: 33.36, 5.39, -4.75
2017-02-17 10:18:41,674 - auto_focus.focus - INFO - Focus: 32.86, 4.89, -4.75
2017-02-17 10:32:48,770 - auto_focus.focus - INFO - Focus: 24.18, 18.06, -4.90
2017-02-17 10:47:19,595 - auto_focus.focus - INFO - Focus: 24.50, 24.50, -4.90
2017-02-17 11:01:48,607 - auto_focus.focus - INFO - Focus: 24.50, 24.70, -5.65
2017-02-17 11:01:54,147 - auto_focus.focus - INFO - Focus: 24.40, 24.70, -5.65
2017-02-17 11:07:44,257 - auto_focus.focus - INFO - Focus: 20.60, 14.28, 1.47
2017-02-17 11:08:14,898 - auto_focus.focus - INFO - Focus: 20.61, 14.25, 1.47
2017-02-17 11:08:36,038 - auto_focus.focus - INFO - Focus: 20.51, 14.00, 1.22
2017-02-17 11:11:18,588 - auto_focus.focus - INFO - Focus: 21.48, 13.86, 1.27
2017-02-17 11:11:26,898 - auto_focus.focus - INFO - Focus: 21.47, 13.89, 1.27
2017-02-17 12:01:29,477 - auto_focus.focus - INFO - Focus: 14.35, 10.55, 0.97
2017-02-17 12:01:38,058 - auto_focus.focus - INFO - Focus: 14.34, 10.58, 0.82
2017-02-17 12:01:46,380 - auto_focus.focus - INFO - Focus: 14.33, 10.57, 0.72
2017-02-17 12:10:30,028 - auto_focus.focus - INFO - Focus: 25.95, 24.87, -8.01
2017-02-17 12:21:45,466 - auto_focus.focus - INFO - Focus: 13.57, 28.64, -8.06
2017-02-17 12:29:17,167 - auto_focus.focus - INFO - Focus: 27.79, 25.23, 0.22
2017-02-17 12:29:25,197 - auto_focus.focus - INFO - Focus: 27.78, 25.18, 0.27
2017-02-17 12:29:54,046 - auto_focus.focus - INFO - Focus: 24.95, 25.07, 0.12
2017-02-17 12:30:02,476 - auto_focus.focus - INFO - Focus: 24.70, 25.30, 0.17
2017-02-17 12:30:10,667 - auto_focus.focus - INFO - Focus: 24.73, 25.49, 0.37
2017-02-17 14:26:18,644 - auto_focus.focus - INFO - Focus: 25.28, 7.29, -1.52
2017-02-17 14:26:26,953 - auto_focus.focus - INFO - Focus: 25.23, 7.28, -1.72
2017-02-17 14:26:54,374 - auto_focus.focus - INFO - Focus: 27.17, 11.98, -1.97
2017-02-17 14:27:09,823 - auto_focus.focus - INFO - Focus: 27.12, 12.08, -1.87
2017-02-17 14:27:21,634 - auto_focus.focus - INFO - Focus: 27.12, 12.08, -1.72
2017-02-17 14:27:34,733 - auto_focus.focus - INFO - Focus: 27.12, 12.03, -1.72
2017-02-17 14:29:18,624 - auto_focus.focus - INFO - Focus: 22.97, 14.42, -1.72
2017-02-17 17:17:49,618 - auto_focus.focus - INFO - Focus: 22.10, 25.35, 0.85
2017-02-17 17:18:01,963 - auto_focus.focus - INFO - Focus: 22.05, 25.30, 1.15
2017-02-17 17:20:06,266 - auto_focus.focus - INFO - Focus: 33.01, 24.52, 1.00
2017-02-17 17:20:17,186 - auto_focus.focus - INFO - Focus: 32.81, 24.57, 0.65
2017-02-17 17:20:28,345 - auto_focus.focus - INFO - Focus: 32.81, 24.62, 0.60
2017-02-17 17:21:30,176 - auto_focus.focus - INFO - Focus: 32.86, 24.67, 0.50
2017-02-17 17:44:51,565 - auto_focus.focus - INFO - Focus: 25.33, 6.28, 0.45
2017-02-17 17:50:37,844 - auto_focus.focus - INFO - Focus: 24.60, 24.80, 0.45
2017-02-17 17:55:33,953 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0722F420>, trait: resolution, old value: 101, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 500.0 <type 'float'> was specified.
2017-02-17 18:13:15,578 - auto_focus.focus - INFO - Focus: 44.72, 2.81, -0.33
2017-02-17 18:16:54,417 - auto_focus.focus - INFO - Focus: 24.70, 24.65, -0.03
2017-02-17 18:17:05,818 - auto_focus.focus - INFO - Focus: 24.40, 24.25, 0.32
2017-02-17 18:17:16,987 - auto_focus.focus - INFO - Focus: 24.05, 24.25, 0.62
2017-02-17 18:17:28,207 - auto_focus.focus - INFO - Focus: 23.65, 24.25, 0.87
2017-02-17 18:17:39,517 - auto_focus.focus - INFO - Focus: 23.35, 24.60, 0.87
2017-02-17 18:21:09,388 - auto_focus.focus - INFO - Focus: 23.20, 24.95, 1.22
2017-02-17 18:21:21,078 - auto_focus.focus - INFO - Focus: 23.15, 25.20, 1.27
2017-02-17 18:32:30,789 - auto_focus.focus - INFO - Focus: 30.50, 22.31, 1.57
2017-02-17 18:32:42,489 - auto_focus.focus - INFO - Focus: 30.75, 21.96, 1.57
